import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  RippleGlobalOptions,
  MatCommonModule,
  MAT_RIPPLE_GLOBAL_OPTIONS,
  MatNativeDateModule,
  MatDialogModule,
  MatSnackBarModule,
  MatCheckboxModule,
  MatButtonModule,
  MatTooltipModule,
  MatDatepickerModule,
  MatOptionModule,
  MatMenuModule,
  MatButtonToggleModule,
  MatInputModule,
  MatFormFieldModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatSelectModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSliderModule,
  MatExpansionModule,
  MatTabsModule,
  MatRadioModule,
  MatSidenavModule,
  MatListModule,
  MatGridListModule,
  MatChipsModule,
  MatSlideToggleModule,
  MatBadgeModule
} from '@angular/material';

const globalRippleConfig: RippleGlobalOptions = {
  disabled: true
};

@NgModule({
  imports: [
    MatCommonModule,
    MatNativeDateModule,
    MatDialogModule,
    MatSnackBarModule,
    MatCheckboxModule,
    MatButtonModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatOptionModule,
    MatMenuModule,
    MatButtonToggleModule,
    MatInputModule,
    MatFormFieldModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSelectModule,
    FormsModule,
    ReactiveFormsModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSliderModule,
    MatExpansionModule,
    MatRadioModule,
    MatSidenavModule,
    MatListModule,
    MatGridListModule,
    MatChipsModule,
    MatSlideToggleModule,
    MatBadgeModule
  ],
  providers: [
    { provide: MAT_RIPPLE_GLOBAL_OPTIONS, useValue: globalRippleConfig }
  ],
  exports: [
    MatCommonModule,
    MatNativeDateModule,
    MatDialogModule,
    MatSnackBarModule,
    MatCheckboxModule,
    MatButtonModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatOptionModule,
    MatMenuModule,
    MatButtonToggleModule,
    MatInputModule,
    MatFormFieldModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSelectModule,
    FormsModule,
    ReactiveFormsModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSliderModule,
    MatExpansionModule,
    MatTabsModule,
    MatRadioModule,
    MatSidenavModule,
    MatListModule,
    MatGridListModule,
    MatChipsModule,
    MatSlideToggleModule,
    MatBadgeModule
  ]
})
export class MaterialUiModule { }
